//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassesDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avenant
    {
        internal int idAvenant { get; set; }
        internal System.DateTime Date { get; set; }
        internal string MotifAvenant { get; set; }
        internal int numeroAvenant { get; set; }
    
        public virtual Contrats Contrats { get; set; }
    }
}
