//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassesDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratInterim : Contrats
    {
        internal string Agence { get; set; }
        internal double Salaire { get; set; }
        internal System.DateTime DateFin { get; set; }
        internal string Motif { get; set; }

        public ContratInterim()
        {

        }
    }
}
