//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassesDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrats
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contrats()
        {
            this.Avenant = new HashSet<Avenant>();
        }

        public int NumContrat { get; set; }
        public bool Statut { get; set; }
        public string Qualification { get; set; }
        public string Libelle { get; set; }
        public string Fonction { get; set; }
        public System.DateTime DateDebut { get; set; }
        public int idContrat { get; set; }
    
        public virtual Collaborateurs Collaborateurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Avenant> Avenant { get; set; }
    }
}
