//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassesDAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lesCollaborateursContainer : DbContext
    {
        public lesCollaborateursContainer()
            : base("name=lesCollaborateursContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Collaborateurs> CollaborateursSet { get; set; }
        public virtual DbSet<Contrats> ContratsSet { get; set; }
        public virtual DbSet<Augmentations> AugmentationsSet { get; set; }
        public virtual DbSet<Avenant> AvenantSet { get; set; }

        public Collaborateurs Collaborateurs
        {
            get => default(Collaborateurs);
            set
            {
            }
        }
    }
}
