//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABIenCouche
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratStage : Contrats
    {
        internal string Ecole { get; set; }
        internal System.DateTime DateFin { get; set; }
        internal string Motif { get; set; }
        internal string Mission { get; set; }
        internal string Tuteur { get; set; }
    }
}
